export const CONFIG = {
  MODEL: 'gpt-5',
  NON_STREAMING: true,

  MAX_COMPLETION_TOKENS: 5000,
  MAX_TOTAL_TOKENS: 20000,

  MAX_USER_CHARS: 4000,
  TOKEN_PER_CHAR_EST: 0.25,

  HTTP_TIMEOUT_MS: 20000,
  FIRST_RETRY_DELAY_MS: 250,
  MAX_RETRIES: 2,

  DEBUG: false
} as const;
